services:
  app:
    build: 
      context : . 
      dockerfile: app/Dockerfile
    restart: unless-stopped
    # Load environment variables from external .env file
    env_file:
      - .env

    volumes:
      # Mount secrets directory as read-only
      - ./secrets:/run/secrets:ro

      # Mount application configuration files as read-only
      - ./config:/app/config:ro

      # Persistent data volume
      - ./data:/app/data

      # Application logs (can be collected or monitored externally)
      - ./logs:/app/logs

      # Custom scripts: entrypoint, init, healthcheck, etc.
      - ./scripts:/app/scripts:ro

    # Internal Docker network
    networks:
      - backend

    # Expose container port to host
    ports:
      - "8080:80"  # host:container

networks:
  backend:
    driver: bridge
